#!/bin/bash
#This is run every time X is starting
#Can be symlinked to users .xinitrc
#Exec bit is important to run script in bash, not sh


#if no connected monitor set resolution for x11vnc
re='\<connected\>' #find word
if [[ ! `xrandr -q` =~ $re ]]; then
    echo "XRANDR: Did not find connected monitor will set fake resolution"
    xrandr --fb 1024x768
else
    echo "XRANDR: Connected monitor detected will use native resolution"
fi


#Startx VNC server
if [[ -e /hive-config/vnc-password.txt ]]; then
	cp /hive-config/vnc-password.txt /tmp/vnc-password.txt
	dos2unix-safe /tmp/vnc-password.txt
	x11vnc -display :0 -rfbport 5900 -no6 -forever -shared -passwdfile /tmp/vnc-password.txt &
else
	echo "No /hive-config/vnc-password.txt then no VNC"
fi
#-nopw
#> /var/log/x11vnc.log 2>&1 &


#enable kill X server with keyboard
setxkbmap -option "terminate:ctrl_alt_bksp"

#display no sleep
#setterm -blank 0
#setterm -powersave off
#xset -dpms


#taskbar
tint2 &

#wallpaper
(sleep 2 && feh --bg-fill --no-fehbg /hive/share/images/wallpaper.jpg) &


termcmd=""


#amd-oc-safe
#[[ $? = 0 ]] &&
#    termcmd+="cat /var/log/amd-oc.log;"

termcmd+="amd-oc-safe;"


#cat /sys/class/drm/card0/device/power_dpm_force_performance_level
#cat /sys/class/drm/card0/device/pp_dpm_sclk



#NVIDIA OC is there are GPUs
GPU_COUNT_NVIDIA=`gpu-detect NVIDIA`
NVIDIA_OC_CONF="/hive-config/nvidia-oc.conf"
[[ $GPU_COUNT_NVIDIA > 0 && -e $NVIDIA_OC_CONF ]] &&
	echo "> Nvidia OC" &&
#    nvidia-oc > /var/log/nvidia-oc.log 2>&1 &&
#    termcmd+="cat /var/log/nvidia-oc.log;"
    termcmd+="nvidia-oc-log;"


roxargs="--replace --maximise"
(lsb_release -a 2>&1 | grep -q '16\.04') && roxargs+=' --disable-sm'
roxterm $roxargs -e bash -c "$termcmd motd; firstrun; ([ -e /home/user/xinit.user.sh ] && bash /home/user/xinit.user.sh); bash" &




openbox-session

