#!/usr/bin/env bash

MINER_NAME="bminer"
[ -t 1 ] && . colors

[[ `ps aux | grep "\./bminer " | grep -v grep | wc -l` != 0 ]] &&
	echo "$MINER_NAME is already running" &&
	exit 1




function config_gen() {
	MINER_CONFIG_FILE="/hive/$MINER_NAME/bminer.conf"

	[ ! -f $WALLET_CONF ] && echo -e "${RED}No wallet config $WALLET_CONF${NOCOLOR}" && return 1

	. $RIG_CONF
	. $WALLET_CONF

	[[ -z $BMINER_URL ]] && echo -e "${YELLOW}BMINER_URL is empty, skipping config generation${NOCOLOR}" && return 1
	[[ -z $BMINER_TEMPLATE ]] && echo -e "${YELLOW}BMINER_TEMPLATE is empty, skipping config generation${NOCOLOR}" && return 1

	echo "Generating $MINER_CONFIG_FILE"

	conf="-api 127.0.0.1:1880 -max-temperature 82"

	tpl=$BMINER_TEMPLATE
	#Don't remove until Hive 1 is gone
#	[[ -z $EWAL && -z $ZWAL && -z $DWAL ]] && echo -e "${RED}No WAL address is set${NOCOLOR}"
	[[ ! -z $EWAL ]] && tpl=$(sed "s/%EWAL%/$EWAL/g" <<< $tpl) #|| echo "${RED}EWAL not set${NOCOLOR}"
	[[ ! -z $ZWAL ]] && tpl=$(sed "s/%ZWAL%/$ZWAL/g" <<< $tpl) #|| echo "${RED}ZWAL not set${NOCOLOR}"
	[[ ! -z $DWAL ]] && tpl=$(sed "s/%DWAL%/$DWAL/g" <<< $tpl) #|| echo "${RED}DWAL not set${NOCOLOR}"
	[[ ! -z $WORKER_NAME ]] && tpl=$(sed "s/%WORKER_NAME%/$WORKER_NAME/g" <<< $tpl) #|| echo "${RED}WORKER_NAME not set${NOCOLOR}"
	[[ ! -z $EMAIL ]] && tpl=$(sed "s/%EMAIL%/$EMAIL/g" <<< $tpl)
	#tpl=$(sed 's/@/%40/g; s/\//%2F/g; s/ /%20/g' <<< $tpl) #HTML special chars
	tpl=$(sed 's/\//%2F/g; s/ /%20/g' <<< $tpl)

	[[ ! -z $BMINER_PASS ]] && tpl+=":$BMINER_PASS"

	grep -q "://" <<< $BMINER_URL
	if [[ $? -ne 0 ]]; then #protocol not found
		uri="stratum://$tpl@$BMINER_URL"
	else
		uri=$(sed "s/:\/\//:\/\/$tpl@/g" <<< $BMINER_URL) #replace :// with username
	fi
	conf+=" -uri $uri"

	[[ ! -z $BMINER_USER_CONFIG ]] && conf+=" $BMINER_USER_CONFIG"

	echo "$conf" > $MINER_CONFIG_FILE
}


config_gen



cd /hive/$MINER_NAME
while true
do
	miner logrotate $MINER_NAME
	/hive/$MINER_NAME/bminer.sh
	echo ""
	echo -e "${YELLOW}$MINER_NAME exited, waiting to cooldown a bit${NOCOLOR}"
	echo ""
	sleep 3
done
