#!/usr/bin/env bash

if [[ ! -d /var/www/html/repomirror ]]; then
	echo "Creating /var/www/html/repomirror"
	mkdir -p /var/www/html/repomirror
fi


#check if nginx config is linked
if [[ ! -L /etc/nginx/sites-enabled/hive-repo.conf ]]; then
	echo "Linking /etc/nginx/sites-enabled/hive-repo.conf"
	rm /etc/nginx/sites-enabled/hive-repo.conf > /dev/null 2>&1
	ln -sf /hive/opt/repomirror/etc/nginx/sites-enabled/hive-repo.conf /etc/nginx/sites-enabled/hive-repo.conf
fi


if [[ ! -e /etc/cron.hourly/hive-updaterepo ]]; then
	echo "Linking /etc/cron.hourly/hive-updaterepo"
	ln -sf /hive/opt/repomirror/etc/cron.hourly/hive-updaterepo /etc/cron.hourly/hive-updaterepo
fi



[[ -e /etc/nginx/sites-enabled/default ]] &&
	rm -f /etc/nginx/sites-enabled/default

/usr/sbin/nginx -s reload


echo ""
echo "Mirror is synced every hour."
echo "Check logs in /var/log/hive-repo-sync.log or run sync manually /etc/cron.hourly/hive-updaterepo."
echo "To give alternate repo fetching URL please put it in /hive-config/repo-sync.url"