#!/usr/bin/env bash

#[ -t 1 ] &&
. colors

n=`gpu-detect AMD`

if [[ $n == 0 ]]; then
	echo "No AMD GPUs detected"
	exit 1
fi

filename=${@:${#@}} #last param

if [[ -z $filename ]]; then
	echo "Flashes VBIOS to all available AMD GPUs"
	echo "Usage: `basename $0` <biosfile.rom>";
	exit 1
fi

extra_args=
for ((i=1; i<=(($#-1)); i++)); do
  extra_args="$extra_args ${!i}"
done


for (( gpu_index=0; gpu_index < $n; gpu_index++ )); do
	echo -e "${PURPLE}=== Flashing card $gpu_index ===${NOCOLOR}"
	#echo "atiflash -p $i $extra_args $filename"

	#gpu_index_hex=$gpu_index
	#[[ $gpu_index -gt 9 ]] && gpu_index_hex=`printf "\x$(printf %x $((gpu_index+55)))"` #convert 10 to A, 11 to B, ...

	amdvbflash -p $gpu_index $extra_args $filename
done
