#!/bin/bash

n=`gpu-detect AMD`

if [[ $n == 0 ]]; then
	echo "No AMD GPUs detected"
	exit 1
fi

filename=${@:${#@}} #last param

if [[ -z $filename ]]; then
	echo "Flashes VBIOS to all available AMD GPUs"
	echo "Usage: `basename $0` <biosfile.rom>";
	exit 1
fi

extra_args=
for ((i=1; i<=(($#-1)); i++)); do
  extra_args="$extra_args ${!i}"
done


for (( i=0; i < $n; i++ )); do
	echo "=== Flashing card $i ==="
	#echo "atiflash -p $i $extra_args $filename"
	atiflash -p $i $extra_args $filename
done
