#!/usr/bin/env bash
#source /etc/environment
. colors

gpu_detect_json="/run/hive/gpu-detect.json"
gpu_stats_json="/run/hive/gpu-stats.json"

export DISPLAY=":0"

NS='/usr/bin/nvidia-settings'
#AUTOFAN_LOG="/var/log/hive-autofan.log"

RIG_CONF="/hive-config/rig.conf"
CONF_FILE="/hive-config/autofan.conf"

#MIN_COEF=80
#MAX_COEF=100
#SLEEP_TIME=20
DEF_SLEEP_TIME=30


#######################################################################
#settings (for autofan.conf without DEF_), default values
#target GPU temperature
DEF_TARGET_TEMP=
#minimal fan speed
DEF_MIN_FAN=30
#maximum fan speed
DEF_MAX_FAN=100
#temperature of stop miner
DEF_CRITICAL_TEMP=85
#AMD fan control (AMD control enable-0/AMD control disable-1)
DEF_NO_AMD=0
#######################################################################



#we will restart miner only it was stopped by this script
miner_stopped_by_overheat=0

###
# Log write
function echo2 {
	#echo -e "$1" > /dev/tty1
	#echo -e "$1" >> $AUTOFAN_LOG
	echo -e "$1"
}

#check $gpu_detect_json and do nothing while not exist
while true; do 
	if [ -f $gpu_detect_json ]; then
		gpu_detect_json=`cat $gpu_detect_json`
		# TODO this block must be refactored to library functions
		amd_indexes_query='[ . | to_entries[] | select(.value.brand == "amd") | .key ]'
		amd_indexes_array=`echo "$gpu_detect_json" | jq -r "$amd_indexes_query | .[]"`
		amd_cards_number=`echo "$gpu_detect_json" | jq -c "$amd_indexes_query | length"`

		nvidia_indexes_query='[ . | to_entries[] | select(.value.brand == "nvidia") | .key ]'
		nvidia_indexes_array=`echo "$gpu_detect_json" | jq -r "$nvidia_indexes_query| .[]"`
		nvidia_cards_number=`echo "$gpu_detect_json" | jq -c "$nvidia_indexes_query | length"`

		# TODO cpus maybe required to use autofans too
		#cpu_indexes_query='[ . | to_entries[] | select(.value.brand == "cpu") | .key ]'
		#cpu_indexes_array=`echo "$gpu_detect_json" | jq -r "$cpu_indexes_query"`
		#cpu_cores_number=`echo "$gpu_detect_json" | jq -c "$cpu_indexes_query | length"`
		declare -a card_bus_ids_array=(`echo "$gpu_detect_json" | jq -r '[ . | to_entries[] | select(.value) | .value.busid ] | .[]'`)
		# TODO There is must be the way to remove space or use the whole value inside the quotes
		#declare -a card_names_array=(`echo "$gpu_detect_json" | jq '[ . | to_entries[] | select(.value) | .value.name ] | .[]'`)
		
		#set AMD $cardnum array
		if [[ $amd_cards_number > 0 ]]; then
			cardnum=()
			for j in ${amd_indexes_array[@]}
			do
				#get bus_id amd gpu
				cardnum_bus_id=${card_bus_ids_array[j]}
				dirs=`ls -d1 /sys/class/drm/card*/device/pp_table | sort --version-sort` #natural sort for 10+ cards
				[[ -z $dirs ]] && break
				for dir in $dirs; do
					basedir=${dir%/*} #cut off /pp_table
					busid_dirs=`cat $basedir/uevent | grep PCI_SLOT_NAME | awk -F= '{print substr($2,6)}'`
					if [[ $busid_dirs == $cardnum_bus_id ]]; then
						[[ $dir =~ \/card([0-9a-z]+)\/ ]]
						cardnum[$j]=${BASH_REMATCH[1]}
					fi
				done
			done
		fi
		break
	else
		echo2 "${RED}No $gpu_detect_json file exist${NOCOLOR}"
	fi
	sleep 10
done


check_gpu () {
	if [[ $nvidia_indexes_array == '[]' && $amd_indexes_array == '[]' ]]; then
		echo2 "No ${RED}AMD${NOCOLOR} or ${GREEN}NVIDIA${NOCOLOR} cards detected"
		exit 1
	fi

	[[ $nvidia_cards_number > 0 ]] &&
		echo2 "You have ${GREEN}NVIDIA${NOCOLOR} GPU's: $nvidia_cards_number" && 
			nvidia-smi -pm 1 > /dev/null 2>&1 && $NS -a GPUPowerMizerMode=1 > /dev/null 2>&1

	[[ $amd_cards_number > 0 ]] &&
		echo2 "You have ${RED}AMD${NOCOLOR} GPU's: $amd_cards_number"

	#check config
	if [ ! -f $CONF_FILE ]; then
		echo2 "${RED}No config $CONF_FILE${NOCOLOR}"
	fi
}



get_fan_speed () {
	local cur_temp=$1
	local prev_temp=$2
	local cur_fan_speed=$3
	local gpu_bus_id=$4
	local i=$5

	target_fan_speed=
	#check current temp and set fan speed
	if [[ $prev_temp -ne 0 && $cur_temp -gt $TARGET_TEMP ]]; then #current temp 
		if [[ $cur_temp -lt $prev_temp ]]; then #adjustment from 2 degrees 
			target_fan_speed=$(( $cur_fan_speed-1 ))
		elif [[ $cur_temp -ge $prev_temp ]]; then
			target_fan_speed=$(( $cur_fan_speed+($cur_temp-$TARGET_TEMP-1) ))
		fi 
	elif [[ $prev_temp -ne 0 && $cur_temp -lt $TARGET_TEMP ]]; then
		if [[ $cur_temp -gt $prev_temp ]]; then #adjustment from 2 degrees
			target_fan_speed=$(( $cur_fan_speed+1 ))
			#high speed adjustment if growing more then 2 degrees 
			[[ $(($cur_temp-2)) -gt $prev_temp ]] && 
				target_fan_speed=$(( $cur_fan_speed+($cur_temp-$prev_temp) ))
		elif [[ $cur_temp -le $prev_temp ]]; then
			target_fan_speed=$(( $cur_fan_speed+($cur_temp-$TARGET_TEMP+1) ))
		fi
	fi

	#doing nothing
	[[ $cur_temp -eq $TARGET_TEMP || $prev_temp -eq 0 ]] && 
		target_fan_speed=$cur_fan_speed
	#+/-1 degree do nothing
	[[ $cur_temp -eq $(( $TARGET_TEMP+1 )) || 
		$cur_temp -eq $(( $TARGET_TEMP-1 )) ]] && target_fan_speed=$cur_fan_speed

	
	#set MIN_FAN & MAX_FAN speed if need
	[[ $target_fan_speed -lt $MIN_FAN ]] && target_fan_speed=$MIN_FAN
	[[ $target_fan_speed -gt $MAX_FAN ]] && target_fan_speed=$MAX_FAN


	#coloring and set sleep time
	echo_temp="$cur_temp°C"
	
	#sleep 3/4
	[[ $cur_temp -lt $TARGET_TEMP && $cur_temp -ne $(( $TARGET_TEMP-1 )) ]] && 
		echo_temp="${BLUE}$cur_temp°C${NOCOLOR}" && NEW_SLEEP_TIME=$(( $DEF_SLEEP_TIME/4*3 ))
	
	#sleep 1
	[[ $cur_temp -eq $(( $TARGET_TEMP-1 )) ]] && echo_temp="${CYAN}$cur_temp°C${NOCOLOR}"
	
	#sleep 1/3
	[[ $cur_temp -gt $TARGET_TEMP && $cur_temp -ne $(( $TARGET_TEMP+1 )) ]] && 
		echo_temp="${RED}$cur_temp°C${NOCOLOR}" && NEW_SLEEP_TIME=$(( $DEF_SLEEP_TIME/3 ))
	
	#sleep 1
	[[ $cur_temp -eq $(( $TARGET_TEMP+1 )) ]] && echo_temp="${YELLOW}$cur_temp°C${NOCOLOR}" 
	
	#less sleep_time
	[[ -n $NEW_SLEEP_TIME && $NEW_SLEEP_TIME -lt $SLEEP_TIME ]] && 
		SLEEP_TIME=$NEW_SLEEP_TIME && NEW_SLEEP_TIME=
	
	
	echo_fan="$target_fan_speed%"
	[[ $target_fan_speed -gt $cur_fan_speed ]] && 
		echo_fan="${YELLOW}$target_fan_speed% ↑${NOCOLOR}"
	[[ $target_fan_speed -lt $cur_fan_speed ]] && 
		echo_fan="${GREEN}$target_fan_speed% ↓${NOCOLOR}"
	[[ $target_fan_speed -eq $MAX_FAN ]] && 
		echo_fan="${RED}$target_fan_speed%${NOCOLOR}"

	[[ $6 == "Nvidia" ]] &&
		gpu_info+="GPU $i ${GREEN}$6${NOCOLOR} [${gpu_bus_id}]: $echo_temp $echo_fan" ||
		gpu_info+="GPU $i ${RED}$6   ${NOCOLOR} [${gpu_bus_id}]: $echo_temp $echo_fan"

	gpu_info+="\n"

#if AMD GPU
	if [[ $6 != "Nvidia" ]]; then
		if [[ $target_fan_speed -gt $cur_fan_speed ]]; then
			[[ $(( $target_fan_speed % 2 )) -eq 1 ]] &&
				target_fan_speed=$(( $target_fan_speed+3 )) || 
					target_fan_speed=$(( $target_fan_speed+2 ))
		elif [[ $target_fan_speed -lt $cur_fan_speed ]]; then
			[[ $(( $target_fan_speed % 2 )) -eq 1 ]] &&
				target_fan_speed=$(( $target_fan_speed+1 )) || 
					target_fan_speed=$(( $target_fan_speed+2 ))
		fi
	fi
#end_if_AMD

#if GPU disable
	[[ -z $cur_temp ]] && 
		target_fan_speed=$MAX_FAN
#
}


###
# What we must to do if temperature reached some limits
check_overheat() {
	if [[ $miner_stopped_by_overheat == 1 && ! `screen -ls | grep "miner"` ]]; then
#	if [[ true ]]; then
		local t
		local allisok=1
		for t in ${temperatures_array[@]}; do
			if [[ $t -ge $TARGET_TEMP ]]; then #cold enough to start miner again
				allisok=0
				break
			fi
		done
		if [[ $allisok == 1 ]]; then
			miner_stopped_by_overheat=0 #let's forget about this
			do_miner_action "miner-start"
			local msg="GPU cooled down, mining resumed"
			echo -en "${GREEN}"
			message ok "$msg"
			echo -en "${NOCOLOR}"
			#echo2 "${GREEN}$msg${NOCOLOR}"
		fi
	elif [[ $miner_stopped_by_overheat == 0 ]]; then
		local t
		for t in ${temperatures_array[@]}; do
			if [[ $t -ge $CRITICAL_TEMP ]]; then
				miner_stopped_by_overheat=1
				do_miner_action "miner-stop"
				local msg="GPU reached ${CRITICAL_TEMP}°C, mining stopped"
				echo -en "${RED}"
				message warning "$msg"
				echo -en "${NOCOLOR}"

				#rebooting if 511
				if [[ $t -gt 100 ]]; then
					local msg="GPU temperature unreal, `uname -n` will be rebooted"
					echo -en "${RED}"
					message warning "$msg"
					echo -en "${NOCOLOR}"
					nohup bash -c 'sreboot' > /tmp/nohup.log 2>&1 &
				fi
				break
			fi
		done
	fi
}


do_miner_action() {
	case $1 in
		"miner-start")
			if [[ ! `screen -ls | grep "miner"` ]]; then
				miner start
				#echo2 "${GREEN}Miner started${NOCOLOR}"
			fi

			if [[ -f $RIG_CONF ]]; then
				. $RIG_CONF
				[[ $WD_ENABLED==1 ]] &&
					wd start
			fi
		;;

		"miner-stop")
			if [[ `screen -ls | grep "miner"` ]]; then
				miner stop
				wd stop
				#echo2 "${RED}Miner stopped${NOCOLOR}"
			fi
		;;
	esac
}



# TODO merge with amd_auto_fan_control
nvidia_auto_fan_control () {
	args=
	#set start index
	i=0
	for index in ${nvidia_indexes_array[@]}
	do
		# TODO Theese fields maybe moved inside `get_fan_speed` replaced by on nvidia_indexes_array[@] as argument
		local gpu_temperature=${temperatures_array[index]}
		local gpu_temperature_previous=${temperatures_array_previous[index]}
		if [[ -z $gpu_temperature_previous ]]; then gpu_temperature_previous=0; fi
		local gpu_fan_speed=${fans_array[index]}
		local card_bus_id=${card_bus_ids_array[index]}
		local brand="Nvidia"
		#event_by_temperature $gpu_temperature
		get_fan_speed $gpu_temperature $gpu_temperature_previous $gpu_fan_speed $card_bus_id $i $brand
		#not set fan_speed if not changed
		[[ -n $target_fan_speed && $target_fan_speed -ne $gpu_fan_speed ]] && 
			args+=" -a [gpu:$i]/GPUFanControlState=1 -a [fan:$i]/GPUTargetFanSpeed=$target_fan_speed"
		i=$(( $i+1 ))
	done
	[[ -n $args ]] && $NS $args > /dev/null 2>&1
}



amd_auto_fan_control () {
	for index in ${amd_indexes_array[@]}
	do
		# TODO Theese fields maybe moved inside `get_fan_speed` replaced by on amd_indexes_array[@] as argument
		local gpu_temperature=${temperatures_array[index]}
		local gpu_temperature_previous=${temperatures_array_previous[index]}
		if [[ -z $gpu_temperature_previous ]]; then gpu_temperature_previous=0; fi
		local gpu_fan_speed=${fans_array[index]}
		local card_bus_id=${card_bus_ids_array[index]}
		local brand="AMD   "
		#event_by_temperature $gpu_temperature
		get_fan_speed $gpu_temperature $gpu_temperature_previous $gpu_fan_speed $card_bus_id $index $brand
		#not set fan_speed if not changed
		[[ $target_fan_speed -ne $gpu_fan_speed ]] && 
			wolfamdctrl -i ${cardnum[index]} --set-fanspeed $target_fan_speed 1>/dev/null
	done
}


auto_fan_control() {
	while true;	do
		TARGET_TEMP= #unset tt if it's not in config anymore
		CRITICAL_TEMP=
		MIN_FAN=
		MAX_FAN=
		NO_AMD=
		
		[[ -f $CONF_FILE ]] && . $CONF_FILE

		#set default values
		[[ -z $TARGET_TEMP ]] && TARGET_TEMP=$DEF_TARGET_TEMP
		[[ -z $CRITICAL_TEMP ]] && CRITICAL_TEMP=$DEF_CRITICAL_TEMP
		[[ -z $MIN_FAN ]] && MIN_FAN=$DEF_MIN_FAN
		[[ -z $MAX_FAN ]] && MAX_FAN=$DEF_MAX_FAN
		[[ -z $NO_AMD ]] && NO_AMD=$DEF_NO_AMD
		SLEEP_TIME=$DEF_SLEEP_TIME


		echo2 "${GREEN}$(date +"%Y-%m-%d %T")${NOCOLOR}"
		#echo2 "${GREEN}¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯${NOCOLOR}"
		#check if exist .conf

		declare -a temperatures_array=(`cat $gpu_stats_json | tail -1 | jq -r ".temp | .[]"`)

		if [[ -n $TARGET_TEMP && -f $CONF_FILE && -f $gpu_stats_json ]]; then
			#MIN_TEMP=$(( TARGET_TEMP-5 ))

			if [[ $PREV_TARGET_TEMP != $TARGET_TEMP || $PREV_CRITICAL_TEMP != $CRITICAL_TEMP || 
				$PREV_MIN_FAN != $MIN_FAN || $PREV_MAX_FAN != $MAX_FAN ]]; then
				echo2 "${PURPLE}Target temp $TARGET_TEMP°C, Miner stop at $CRITICAL_TEMP°C, Min Fan $MIN_FAN%, Max Fan $MAX_FAN%${NOCOLOR}"
				PREV_TARGET_TEMP=$TARGET_TEMP
				PREV_CRITICAL_TEMP=$CRITICAL_TEMP
				PREV_MIN_FAN=$MIN_FAN
				PREV_MAX_FAN=$MAX_FAN
			fi

			declare -a fans_array=(`cat $gpu_stats_json | tail -1 | jq -r ".fan | .[]"`)
			gpu_info=

			if (( $nvidia_cards_number > 0 )); then
				nvidia_auto_fan_control
			fi

			if [[ $amd_cards_number > 0 && $NO_AMD == 0 ]]; then #enabled AMD
				amd_auto_fan_control
			fi

			echo2 "$gpu_info"

			declare -a temperatures_array_previous=(${temperatures_array[@]})

		fi

		#miner_stop will be work 
		check_overheat

		#sleep $SLEEP_TIME
		#echo "SLEEP_TIME=$SLEEP_TIME"
		read -t $SLEEP_TIME
	done
}



case $1 in
	run)
		#check running
#		process_count=`ps aux | grep "autofan" | grep -v grep | grep -v $$ | wc -l`
#		if [[ $process_count -gt 1 ]]; then #this process and another
#			echo -e "${RED}Autofan is already running${NOCOLOR}\nRun ${CYAN}autofan screen${NOCOLOR} to open it"
#			exit 1
#		fi

		check_gpu
		auto_fan_control
	;;

	*)
		session_count=`screen -ls autofan | grep autofan | wc -l`
		if [[ $session_count > 0 ]]; then
			screen -x -S autofan
		else #start new screen
			screen -dm -S autofan autofan run
			echo2 "Autofan screen started"
		fi
	;;

esac
