#!/usr/bin/env bash
#Change password for SSH and VNC
#Parameter: new_password or -conf to get password from rig.conf

#[ -t 1 ] &&
. colors

# Check parameter
if [[ -z $1 ]]; then
	echo -e "${CYAN}Changes system password for \"user\" (SSH and VNC also)${NOCOLOR}"
	echo -e "Specify password as an argument"
	echo -e "Run with \"-conf\" to get a password from rig.conf"
	exit 1
fi


if [[ $1 == "-conf" ]]; then
	if [[ ! -f $RIG_CONF ]]; then
		echo -e "${RED}File $RIG_CONF not found${NOCOLOR}"
		exit 1
	fi
	
	. $RIG_CONF

	if [[ -z $RIG_PASSWD ]]; then
		echo -e "${RED}Variable RIG_PASSWD is empty${NOCOLOR}"
		exit 1
	fi
	
	new_psw=$RIG_PASSWD
	echo -e "Got password from $RIG_CONF"
else
	new_psw=$1
fi

#Change passwords and set SET_RIG_PASS to 0
echo -e "$new_psw\n$new_psw\n" | passwd user > /dev/null 2>&1
sed -i "1s/.*/$new_psw/" "$VNC_PASSWD" #only 1 line

#no need
#sed -i "s/^SET_RIG_PASS=.*/SET_RIG_PASS=/" $RIG_CONF

echo -e "${GREEN}Password changed successfully${NOCOLOR}"

exit 0