#!/usr/bin/env bash

export PATH=/bin:/sbin:/usr/bin:/usr/sbin

SCRIPT_PATH=`dirname $0`
SCRIPT_NAME=`basename $0`
cd $SCRIPT_PATH
mydir=`pwd`
myself="$mydir/$SCRIPT_NAME"

TMPDIR="/tmp/tmphive"
md5_url=
url=
root_dev=""
farm_hash=""
farm=""
force=0
no_confirm=0
smb=0
smbuser=
smbpasswd=
nfs=0
thishive=0
[[ $(uname -sr) == *hive* ]] && thishive=1

#Get root
if [[ $(id -u) -ne 0 ]]; then
	echo "Root privileges required"
	sudo chmod +x $0
	exec sudo $myself $*
fi



BLACK='\033[0;30m'
DGRAY='\033[1;30m'
RED='\033[0;31m'
BRED='\033[1;31m'
GREEN='\033[0;32m'
BGREEN='\033[1;32m'
YELLOW='\033[0;33m'
BYELLOW='\033[1;33m'
BLUE='\033[0;34m'
BBLUE='\033[1;34m'
PURPLE='\033[0;35m'
BPURPLE='\033[1;35m'
CYAN='\033[0;36m'
BCYAN='\033[1;36m'
LGRAY='\033[0;37m'
WHITE='\033[1;37m'
NOCOLOR='\033[0m'






function usage {
	echo -e "${CYAN}Usage: hive-replace [option] <Path or URL to ZIP file with Hive OS image>${NOCOLOR}"
	echo -e
	echo -e "Options:"
	echo -e "${GREEN}  -y|--yes                    ${NOCOLOR}Do not ask for confirmation, answer yes to all questions"
	echo -e "${GREEN}  -f|--force                  ${NOCOLOR}Forced replace. Do not check the checksum of ZIP archive. Use with caution!"
	echo -e "${GREEN}  --nfs                       ${NOCOLOR}To use NFS Shared resource. e.g.: ${GREEN}IP_NFS_server:/shared_dir/hive_zip${NOCOLOR}"
	echo -e "${GREEN}  --smb                       ${NOCOLOR}To use Windows Shared resource. e.g.: ${GREEN}//IP_Windows_comp/shared_folder/hive_zip${NOCOLOR}"
	echo -e "${GREEN}  --smbuser=Windows user      ${NOCOLOR}UserName for Windows Shared resource. Do not set this option for guest/anonymous access"
	echo -e "${GREEN}  --smbpass=Windows password  ${NOCOLOR}Password for Windows Shared resource. Do not set this option for guest/anonymous access"
	echo -e "${GREEN}  --hash=FARM_HASH            ${NOCOLOR}FARM_HASH from Web-interface"
	echo -e "${GREEN}  -h|--help                   ${NOCOLOR}Show this message"
	echo -e
	echo -e "Example:"
	echo -e "${GREEN}  hive-replace -y --hash=46e9602837d0bda99f0 http://mylocalserver/hiveos-0.6-01@181121.zip${NOCOLOR}"
	echo -e "${GREEN}  hive-replace -y -f --hash=46e9602837d0bda99f0 --nfs 192.168.10.100:/home/john/hive/hiveos-0.6-01@181121.zip${NOCOLOR}"
	echo -e "${GREEN}  hive-replace -y -f --hash=46e9602837d0bda99f0 --smb --smbuser=winuser --smbpass=secret //192.168.0.1/shared_folder/hiveos-0.6-01@181121.zip${NOCOLOR}"

	exit
}

# Gets/downloads image
function get {
	cd $TMPDIR
	rm $TMPDIR/*hive* > /dev/null 2>&1

	#Remove interactive	
	#[[ ! -z $url ]] && echo -e  "${GREEN}\nCurrent URL|path to Hive OS image is ${YELLOW}\"$url\"${GREEN}.\nIf this URL|path is correct press ENTER or retype correct URL|path.${NOCOLOR}"
	#echo -en "${GREEN}\nLink|path to ZIP file with Hive OS image (HTTP|FTP link or local|NFS path): ${NOCOLOR}"
	#read answer
	#[[ ! -z $answer ]] && url=$answer
	###

	basename=`basename -s .zip "$url"`
	archname=`basename "$url"`
	
	if [[ $nfs -eq 1 || $smb -eq 1 ]]; then
		[[ ! -d $TMPDIR/share ]] && mkdir $TMPDIR/share
		mnt_flag=1
		mnt_share=1
		cat /proc/mounts | grep $TMPDIR/share > /dev/null 2>&1
		mnt_share=$?
		[[ $mnt_share -eq 0 ]] && mnt_flag=0
		[[ $nfs -eq 1 && $mnt_share -ne 0 ]] && mount -t nfs $(dirname "$url") $TMPDIR/share > /dev/null 2>&1 && mnt_flag=$?
		if [[ $smb -eq 1 && $mnt_share -ne 0 ]]; then
			psw=
			[[ -z $smbuser ]] && smbuser="nobody"
			[[ ! -z $smbpasswd ]] && psw="password=$smbpasswd"
			mount -v -t cifs -o username=$smbuser,$psw,iocharset=utf8,vers=3.0 $(dirname "$url") $TMPDIR/share > /dev/null 2>&1
			mnt_flag=$?
		fi	
		[[ $mnt_flag -ne 0 ]] && echo -e "${RED}Сan't mount network shared resource.${NOCOLOR}" && return 1
		url="$TMPDIR/share/$archname"
	fi
	
	
	#download VERSIONS.txt to get md5 later
	if [[ $force -ne 1 ]]; then
		#default is "http://download.hiveos.farm/VERSIONS.txt"
		md5_url=$(dirname "$url")/VERSIONS.txt
		curl -s $md5_url > $TMPDIR/VERSIONS.txt
		[[ $? -ne 0 ]] && echo -e "${RED}Сan't get $md5_url to check MD5 checksum. Use -f to ignore this.${NOCOLOR}" && return 1
		mdsum=$(sed -n "/$archname/p" $TMPDIR/VERSIONS.txt | awk '{print$2}')
		[[ -z $mdsum ]] && echo -e "${RED}Сan't get md5sum from $md5_url to check MD5 checksum. Use -f to ignore this.${NOCOLOR}" && return 1
	fi

	

	#Copy|download hive image to tmmfs
	echo -e "\n${CYAN}> Downloading image file${NOCOLOR}"
	if [[ "$url" == *http* ||  "$url" == *ftp* ]]; then
		echo ""
		wget -t 5 --show-progress $url
		[[ $? -ne 0 ]] && echo -e "${RED}Download Hive OS image failed. Check url${NOCOLOR}" && return 1
	else
		[[ ! -f $url ]] && echo -e "${RED}Hive OS image not found. Check path${NOCOLOR}" && return 1
		cp -v $url $TMPDIR
		[[ $? -ne 0 ]] && echo -e "${RED}Copy Hive OS image failed${NOCOLOR}" && return 1
	fi
	
	#check md5
	if [[ $force -ne 1 ]]; then
		echo -e "\n${CYAN}> Checking MD5 summ of image file${NOCOLOR}"
		mdsum_hive=$(md5sum $TMPDIR/$archname | awk '{print$1}')
		[[ $mdsum != $mdsum_hive ]] && echo -e "${RED}MD5 checksum of image file does not match${NOCOLOR}\nGot $mdsum_hive, expected $mdsum" && return 1
	fi


	echo -e "${GREEN}Download|copy Hive OS image successful!${NOCOLOR}"
	return 0
}


# Starting actions
function prepare {
	#Prevent start from local console
	[[ $(tty) == *tty* || ! -z $DISPLAY ]] && echo "This script does not work in the local console. Exit" && exit
	
	mem=$(free -m | awk 'NR == 2{print$2}')
	clear
	echo -e "${CYAN}***********************************${NOCOLOR}"
	echo -e "${YELLOW}Hive OS Image Installation${NOCOLOR}"
	echo -e "${CYAN}***********************************${NOCOLOR}"
	echo
	echo "Total RAM=$mem Mb"
	echo
	[[ $mem -lt 3600 ]] && echo -e "${YELLOW}4 Gb RAM is required. Exiting.${NOCOLOR}" && exit

	PART_UUID=`cat /proc/cmdline | tr " " "\n" | grep "UUID" | sed 's/\(^root=UUID=\)//'`
	DISK_PART=`blkid | grep -m1 $PART_UUID | awk '{ print $1 }' | sed 's/://' | sed 's/\(^\/dev\/\)//'`
	DISK_NAME=`echo ${DISK_PART} | sed 's/\([[:digit:]]\)//'`
	DISK_SIZE=`cat /proc/partitions | grep -w "${DISK_NAME}" | awk '{ printf("%.f",$3/1024)}'`
	PART_SIZE=`cat /proc/partitions | grep -w "${DISK_PART}" | awk '{ printf("%.f",$3/1024)}'`


	echo -e "Current OS booted from ${GREEN}$DISK_NAME${NOCOLOR} and whole drive size is ${WHITE}$DISK_SIZE${NOCOLOR} Mb"
	[[ $DISK_SIZE -lt 8192 ]] && echo -e "\n${YELLOW}The minimum disk size for Hive OS is 8 Gb${NOCOLOR}" && exit

	if [[ $no_confirm -ne 1 ]]; then
		echo -e "${RED}Warning: After Hive OS installation, all your data on ${GREEN}$DISK_NAME${NOCOLOR} ${RED}will be lost!${NOCOLOR}"
		echo -en "\nType ${GREEN}\"yes\"${NOCOLOR} if you want to install Hive OS on ${GREEN}$DISK_NAME${NOCOLOR}: "
		read answer
		[[ $answer != "yes" ]] && echo -e "${YELLOW}\nBye, bye!${NOCOLOR}" && exit
	fi

	##check programs
	programs=0
	need_install=
	dpkg -s lsof > /dev/null 2>&1
	[[ $? -ne 0 ]] && programs=1 && need_install="lsof"
	dpkg -s curl > /dev/null 2>&1
	[[ $? -ne 0 ]] && programs=1 && need_install="$need_install curl"
	dpkg -s wget > /dev/null 2>&1
	[[ $? -ne 0 ]] && programs=1 && need_install="$need_install wget"
	dpkg -s unzip > /dev/null 2>&1
	[[ $? -ne 0 ]] && programs=1 && need_install="$need_install unzip"
	if [[ smb -eq 1 ]]; then
		dpkg -s smbclient > /dev/null 2>&1
		[[ $? -ne 0 ]] && programs=1 && need_install="$need_install smbclient"
	fi
	if [[ nfs -eq 1 ]]; then
		dpkg -s nfs-common > /dev/null 2>&1
		[[ $? -ne 0 ]] && programs=1 && need_install="$need_install nfs-common"
	fi
	if [[ $programs -ne 0 ]]; then
		echo -e "${CYAN}> Installing required packages${NOCOLOR}"
		apt-get update
		apt-get install -y $need_install
		[[ $? -ne 0 ]] && echo -e "${RED}Failed to install required packages${NOCOLOR}" && exit
		echo -e "${GREEN}> Installed required packages successfully${NOCOLOR}"
	fi

	#create tmpfs
	cat /proc/mounts | grep $TMPDIR > /dev/null 2>&1
	if [[ $? -ne 0 ]]; then
		mkdir $TMPDIR > /dev/null 2>&1
		mount none $TMPDIR -t tmpfs -o size=3000m
	fi


	#get farm_hash or old config
	[[ $thishive -eq 1 && -f /hive-config/rig.conf ]] && cp /hive-config/rig.conf $TMPDIR/
	
	
	
	
	#Remove interactive
	#	if [[ $thishive -eq 1 && -f /hive-config/rig.conf ]]; then
	#	cp /hive-config/rig.conf $TMPDIR/
	#else
	#	farm=""
	#	while [[ -z $farm ]]; do
	#		echo -en "${GREEN}\nFARM_HASH from Web-interface: ${NOCOLOR}"
	#		read farm
	#		[[ -z $farm ]] && echo "${RED}FAMR_HASH can't be empty. Please retype.${NOCOLOR}"
	#	done
	#fi

	
	#get hive zip
	get
	[[ $? -ne 0 ]] && exit
		
	#flag_get=1
	#while [[ $flag_get -ne 0 ]]; do
	#	get
	#	flag_get=$?
	#	if [[ $flag_get -ne 0 ]]; then
	#		repeat="y"
	#		echo -en "You want to try again (Y/n): "
	#		read answer
	#		[[ ! -z $answer ]] && repeat=$answer
	#		[[ $repeat != y* && $repeat != Y* ]] && echo -e "${YELLOW}\nBye, bye!${NOCOLOR}" && exit
	#	fi
	#done

	#Disable kernel message to tty
	echo 0 > /proc/sys/kernel/printk
	echo 1 > /proc/sys/kernel/sysrq
	echo 0 > /proc/sysrq-trigger


	#stop services and remount RO
	swapoff -a
	echo -e "\n${CYAN}> Stopping services${NOCOLOR}"

	if [[ $thishive -eq 1 ]]; then
		miner stop > /dev/null 2>&1
		wd stop > /dev/null 2>&1
		screen -S autofan -X quit > /dev/null 2>&1
		systemctl stop hivex > /dev/null 2>&1
		[[ ! -z `pidof xinit` ]] && kill -9 `pidof xinit` > /dev/null 2>&1
	fi

	for SOCKET in \
	`systemctl list-units -t socket | awk '{print $1}' | grep -v -e ssh | grep -v -e openvpn | grep -v -e shellinabox | grep -v -e network | grep -v -e ifup | grep -v -e user-sessions | grep -v -e hive`; \
	do systemctl stop $SOCKET > /dev/null 2>&1 && echo "> stop $SOCKET"; done

	for SERVICE in \
	`systemctl list-units -t service | awk '{print $1}' | grep -v -e ssh | grep -v -e openvpn | grep -v -e shellinabox | grep -v -e network | grep -v -e ifup | grep -v -e user-sessions | grep -v -e hive`; \
	do systemctl stop $SERVICE > /dev/null 2>&1 && echo "> stop $SERVICE"; done
	
	pid="1"
	while [[ ! -z $pid ]]; do
		pid=$(lsof / | grep -v ' \(mem\|txt\|rtd\|cwd\) ' | grep -v -e $SCRIPT_NAME | grep -v -e telec | sed '2!d' | awk '{print $2}')
		[[ -z $pid ]] && continue
		process=$(lsof / | grep -v ' \(mem\|txt\|rtd\|cwd\) ' | grep -v -e $SCRIPT_NAME | grep -v -e telec | sed '2!d' | awk '{print $1}')
		echo -e "> kill $process"
		kill $pid
		sleep 1
	done
	

	#Readonly remount
	for MOUNTS in `cat /proc/mounts | grep $DISK_NAME | awk '{print $2}'`; do
		mount -n -o remount,ro $MOUNTS > /dev/null 2>&1;
	done


	#get config partition and mount it to loop
	arch=$(ls $TMPDIR/*hive*zip)
	unzip -p $arch | dd of=$TMPDIR/conf.img bs=1M count=50 iflag=fullblock > /dev/null 2>&1
	begin_conf=$(( $(fdisk -l $TMPDIR/conf.img | grep NTFS | awk '{print $2}') * 512 ))
	conf_loop=$(losetup -f)
	losetup -o $begin_conf $conf_loop $TMPDIR/conf.img
	mkdir $TMPDIR/hive-config
	mount $conf_loop $TMPDIR/hive-config

	if [[ -f $TMPDIR/rig.conf ]]; then
		cp $TMPDIR/rig.conf $TMPDIR/hive-config/rig.conf
	else
		echo -e "HIVE_HOST_URL=\"http://api.hiveos.farm\"" > $TMPDIR/hive-config/rig.conf
		echo -e "FARM_HASH=$farm\n" >> $TMPDIR/hive-config/rig.conf
	fi

	#write image of configs partition
	dd if=$conf_loop of=$TMPDIR/new_conf.img > /dev/null 2>&1


	#create temp root
	echo -e "\n${CYAN}> Creating temporary root filesystem${NOCOLOR}"
	mkdir -p $TMPDIR/{proc,sys,run,dev,usr,var,oldroot,bin,sbin,lib,tmp,usr/lib,usr/share,usr/lib/x86_64-linux-gnu,lib/lsb}
	cp -aR /{bin,sbin,etc} $TMPDIR > /dev/null 2>&1
	cp -aR /usr/{bin,sbin} $TMPDIR/usr > /dev/null 2>&1
	cp -aR /lib/x86_64-linux-gnu $TMPDIR/lib > /dev/null 2>&1
	cp -aR /lib64 $TMPDIR > /dev/null 2>&1
	cp -aR /usr/lib/sudo $TMPDIR/usr/lib > /dev/null 2>&1
	cp -a /usr/lib/x86_64-linux-gnu/libmpfr* $TMPDIR/usr/lib/x86_64-linux-gnu > /dev/null 2>&1
	cp -a /usr/lib/x86_64-linux-gnu/libsigsegv* $TMPDIR/usr/lib/x86_64-linux-gnu > /dev/null 2>&1
	cp -a /usr/lib/x86_64-linux-gnu/libgmp* $TMPDIR/usr/lib/x86_64-linux-gnu > /dev/null 2>&1
	cp -aR /dev $TMPDIR > /dev/null 2>&1
	cp $myself $TMPDIR > /dev/null 2>&1
	chmod +x $TMPDIR/$SCRIPT_NAME > /dev/null 2>&1

	mount --bind /proc $TMPDIR/proc
	mount --bind /sys $TMPDIR/sys
	mount --bind /dev $TMPDIR/dev

	#create conf for second part
	echo "wr=1" > $TMPDIR/replace.conf
	echo "root_dev=$DISK_NAME" >> $TMPDIR/replace.conf
	echo "conf_loop=$conf_loop" >> $TMPDIR/replace.conf


	#chroot to temp root
	mount --bind /proc $TMPDIR/proc
	mount --bind /sys $TMPDIR/sys
	mount --bind /dev $TMPDIR/dev
	sync
	cd $TMPDIR
	exec chroot . /bin/bash /$SCRIPT_NAME
}


# Writing to disk
function write {

	cd /

	arch=$(ls *hive*zip)
	conf_part=$root_dev"1"

	echo -e "\n${CYAN}> Writing Hive OS filesystem to $root_dev${NOCOLOR}"
	echo -e "Please wait, this can take long"
	echo -e "To prevent damage to your disk device\ndo not turn off your computer until the end of the process.\n"

	unzip -p $arch | dd of=/dev/$root_dev status=progress bs=20M
	[[ $? -ne 0 ]] && echo -e "Write image failed. Exiting." && return


	#Rewrite config partition
	partprobe > /dev/null 2>&1
	dd if=/new_conf.img of=/dev/$conf_part > /dev/null 2>&1


	#Reboot
	sync

	echo -e
	echo -e "${GREEN}Image writing to ${PURPLE}$root_dev${GREEN} is successfull!${NOCOLOR}"
	echo -e
	echo -e "Your rig is configured and ready to work under Hive OS."
	echo -e "After reboot it should appear on the web."
	echo -e
	echo -e "${GREEN}Have a happy mining!${NOCOLOR}"
	echo -e "${YELLOW}Rebooting in 15 seconds${NOCOLOR}"

	sleep 15

	echo 1 > /proc/sys/kernel/sysrq
	echo b > /proc/sysrq-trigger
}



function sel {
	wr=0
	[[ -f replace.conf ]] && source /replace.conf

	if [[ $wr -ne 1 ]]; then
		[[ -z $url ]] && echo -e "${YELLOW}Filesystem path or URL to Hive OS image is required.${NOCOLOR}\n" && usage
		prepare
	else
		write
	fi
}


[[ $1 == "-h" || $1 == "--help" ]] && usage

for param in "$@"; do
	case "$param" in
		-f|--force)
			force=1
		;;
		-y|--yes)
			no_confirm=1
		;;
		--nfs)
			nfs=1
		;;
		--smb)
			smb=1
		;;
		--smbuser=*)
			smbuser="${param#*=}"	
		;;
		--smbpass=*)
			smbpasswd="${param#*=}"	
		;;
		--hash=*)
			farm="${param#*=}"
		;;
		*hive*zip)
			url=$param
		;;
		*)
			#none
		;;
	esac
done

[[ $nfs -eq 1 && $smb -eq 1 ]] && echo -e "${YELLOW}Specify only one of the options: ${GREEN}--smb${NOCOLOR} or ${GREEN}--nfs${NOCOLOR}. Both are not allowed${NOCOLOR}\n" && usage
if [[ $nfs -eq 1 || $smb -eq 1 ]]; then
	[[ "$url" == *http* ||  "$url" == *ftp* ]] && echo -e "${YELLOW}--nfs or --smb and http or ftp - incompatible\n" && usage
fi

sel
