#!/usr/bin/env bash
# Uninstall all miners packages to save space
# Optional argument "nostart" - don't run miners
# Optional argument "noinstall" - don't install default packages


[ -t 1 ] && . colors

packages=`apt list --installed 'hive-miners-*' 2>&1 | grep -o "hive-miners-.*-.*/"`
[[ -z $packages ]] && echo "Nothing to uninstall" && exit 0


echo -e "${CYAN}> Stopping miner${NOCOLOR}"
miner stop

echo
echo -e "${CYAN}> Uninstalling packages${NOCOLOR}"
for package_name in $packages; do
	package_name=${package_name//\//}
	echo -e "${YELLOW}- $package_name${NOCOLOR}"

	apt remove -y $package_name

	echo
done

apt-get -y autoremove
apt-get clean



echo
[[ $1 == "noinstall" ]] &&
	echo -e "${CYAN}> Skipping installing default miners${NOCOLOR}" &&
	exit 0


echo -e "${CYAN}> Checking miners default installation${NOCOLOR}"
. $RIG_CONF

for mindex in {1..32}; do
	[[ $mindex == 1 ]] && mindex=
	eval minerval=\$MINER$mindex
	if [[ ! -z $minerval ]]; then
		package_name="hive-miners-$minerval"
		dpkg -s $package_name > /dev/null 2>&1
		if [[ $? -ne 0 ]]; then
			echo -e "${YELLOW}+ $package_name${NOCOLOR}"
			apt-get install -y $package_name
			echo
		fi
	fi
done




echo
[[ $1 == "nostart" || $1 == "noinstall" ]] &&
	echo -e "${CYAN}> Skipping restarting miner${NOCOLOR}" &&
	exit 0

echo -e "${CYAN}> Restarting miner${NOCOLOR}"
miner start