#!/usr/bin/env bash
. colors

#------------------------------------------------------------------------------------------------------------------

function update() {
	#apt-get update -o Dir::Etc::sourcelist=hiverepo.list
	#apt-get update
	apt-get update -o Dir::Etc::sourcelist="sources.list.d/hiverepo.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
	exitcode=$?
	[[ $exitcode -ne 0 ]] &&
		echo -e "${RED}Repository update failed${NOCOLOR}" &&
		return $exitcode ##don't exit as some mirrors can fail

	return 0
}

#------------------------------------------------------------------------------------------------------------------

function list() {
	suffix=
	[[ ! -z $1 ]] && suffix="-$1"

	apt list --installed "hive$suffix*" 2>&1
}

#------------------------------------------------------------------------------------------------------------------

function getlist() {
	packages=$(list $1 | grep -o "hive.*/")
	for package_name in $packages; do
		package_name=${package_name//\//}
		echo "$package_name"
	done
}

#------------------------------------------------------------------------------------------------------------------

function remove_miners() {
	#packages=`apt list --installed 'hive-miners-*' 2>&1 | grep -o "hive-miners-.*-.*/"`
	packages=$(getlist miners)
	[[ -z $packages ]] && echo "Nothing to uninstall" && exit 0


	echo -e "${CYAN}> Stopping miner${NOCOLOR}"
	miner stop

	echo
	echo -e "${CYAN}> Uninstalling packages${NOCOLOR}"
	for package_name in $packages; do
		#package_name=${package_name//\//}
		echo -e "${YELLOW}- $package_name${NOCOLOR}"

		apt remove -y $package_name

		echo
	done

	apt-get -y autoremove
	apt-get clean



	echo
	if [[ $1 == "noinstall" ]]; then
		echo -e "${CYAN}> Skipping installing default miners${NOCOLOR}"
		exit 0
	fi


	echo -e "${CYAN}> Updating repository${NOCOLOR}"
	update

	echo -e "${CYAN}> Checking miners default installation${NOCOLOR}"
	. $RIG_CONF

	for mindex in {1..32}; do
		[[ $mindex == 1 ]] && mindex=
		eval minerval=\$MINER$mindex
		if [[ ! -z $minerval ]]; then
			package_name="hive-miners-$minerval"
			dpkg -s $package_name > /dev/null 2>&1
			if [[ $? -ne 0 ]]; then
				echo -e "${YELLOW}+ $package_name${NOCOLOR}"
				apt-get install -y -f $package_name
				echo
			fi
		fi
	done

	echo
	[[ $1 == "nostart" || $1 == "noinstall" ]] &&
		echo -e "${CYAN}> Skipping restarting miner${NOCOLOR}" &&
		exit 0

	echo -e "${CYAN}> Restarting miner${NOCOLOR}"
	miner start

}

#------------------------------------------------------------------------------------------------------------------

function install_miners_all() {
	echo -e "${CYAN}> Updating repository${NOCOLOR}"

	update || exit $?

	packages=$(apt list "hive-miners-*" 2>&1 | grep -o "hive-miners-.*/" | grep -v '[0-9]')
	[[ ! -z $1 ]] && #filter packages
		packages=$(echo "$packages" | grep "\-$1/\$") #packages end up with /


	packages_count=0
	[[ ! -z $packages ]] &&
		packages_count=$(echo "$packages" | wc -l)

	[[ $packages_count == 0 ]] &&
		echo -e "${YELLOW}No \"$1\" found in \"hive-miners-*\" packages ${NOCOLOR}" &&
		exit 1

	echo -e "${CYAN}> Installing $packages_count miners${NOCOLOR}"

	for package_name in $packages; do
		package_name=${package_name//\//}

		echo -en "${CYAN}$package_name${NOCOLOR} "

		dpkg -s $package_name > /dev/null 2>&1
		if [[ $? -ne 0 ]]; then
			echo -e "${YELLOW}Installing${NOCOLOR}"

			apt-get install -y -f $package_name 2>&1 | tee /tmp/package-install.log
			exitstatus=${PIPESTATUS[0]}

			[[ $exitstatus -ne 0 ]] &&
				echo -e "${RED}Error installing $package_name${NOCOLOR}"
		else
			echo -e "${GREEN}Installed${NOCOLOR}"
		fi
	done

	apt-get clean

	repover-touch
}


#------------------------------------------------------------------------------------------------------------------




if [[ $1 == "remove" && $2 == "miners" ]]; then
	remove_miners $3
elif [[ $1 == "list" ]]; then
	list $2
elif [[ $1 == "getlist" ]]; then
	getlist $2
elif [[ $1 == "update" ]]; then
	update || exit $?
elif [[ $1 == "install" && $2 == "miners" ]]; then
	install_miners_all $3
else
	echo -e "${CYAN}Hive Package Manager${NOCOLOR}
${YELLOW}update${NOCOLOR} - update packages list from repository
${YELLOW}list${NOCOLOR} - list all installed hive packages
${YELLOW}list miners${NOCOLOR} - list only miners packages
${YELLOW}getlist${NOCOLOR} - list without versions
${YELLOW}remove miners${NOCOLOR} - uninstall miners
${YELLOW}remove miners nostart${NOCOLOR} - don't run miners
${YELLOW}remove miners noinstall${NOCOLOR} - don't run and don't install default packages
${YELLOW}install miners${NOCOLOR} - install all available miners, useful for preparing PXE image
${YELLOW}install miners [ethminer]${NOCOLOR} - install specific miner"
fi

exit 0
