#!/usr/bin/env bash

#[ -t 1 ] &&
. colors

date
echo ""

NVIDIA_OC_CONF="/hive-config/nvidia-oc.conf"
export DISPLAY=":0"

n=`gpu-detect NVIDIA`

if [ $n == 0 ]; then
	echo "No NVIDIA cards detected, exiting"
	exit
fi
echo "Detected $n NVIDIA cards"


if [ ! -f $NVIDIA_OC_CONF ]; then
	echo "$NVIDIA_OC_CONF does not exist"
	exit
fi

source $NVIDIA_OC_CONF


if [[ ! -z $RUNNING_DELAY ]]; then
	echo -e "${CYAN}Sleeping $RUNNING_DELAY seconds...${NOCOLOR}"
	sleep $RUNNING_DELAY
fi



if [[ -z $MEM ]]; then
	:
	#MEM=0
	#echo "ERROR: no MEM set"
	#exit
fi

if [[ -z $CLOCK || $CLOCK == "" ]]; then
	:
	#CLOCK=0
	#echo "ERROR: no CLOCK set"
	#exit
fi

if [[ -z $FAN || $FAN == "" ]]; then
	FAN=0
fi

if [[ -z $PLIMIT || $PLIMIT == "" ]]; then
	PLIMIT=0
fi

if [[ -z $OHGODAPILL_ENABLED || $OHGODAPILL_ENABLED == "" ]]; then
	OHGODAPILL_ENABLED=0
fi

#Start OhGodAnETHlargementPill. It will exit if its 0
OHGODAPILL_RUNNING=`ps aux | grep /hive/opt/ohgodapill/run.sh | grep -v grep | wc -l`
if [[ $OHGODAPILL_ENABLED == 1 ]]; then
	if [[ $OHGODAPILL_RUNNING -eq 0 ]]; then
		echo "> Start OhGodAnETHlargementPill"
		nohup /hive/opt/ohgodapill/run.sh $OHGODAPILL_ARGS > /dev/null 2>&1 &
		sleep 1
		sync
	fi
else
	if [[ $OHGODAPILL_RUNNING -ne 0 ]]; then
		pkill -f '/hive/opt/ohgodapill/run.sh'
		pkill -f '/hive/opt/ohgodapill/OhGodAnETHlargementPill-r2'
	fi
fi



#pad arrays
[[ ! -z $CLOCK ]] &&
CLOCK=($CLOCK) &&
for (( i=${#CLOCK[@]}; i < $n; ++i )); do
	CLOCK[$i]=${CLOCK[$i-1]}
done

[[ ! -z $MEM ]] &&
MEM=($MEM) &&
for (( i=${#MEM[@]}; i < $n; ++i )); do
	MEM[$i]=${MEM[$i-1]}
done

[[ ! -z $FAN ]] &&
FAN=($FAN) &&
for (( i=${#FAN[@]}; i < $n; ++i )); do
	FAN[$i]=${FAN[$i-1]}
done

[[ ! -z $PLIMIT ]] &&
PLIMIT=($PLIMIT) &&
for (( i=${#PLIMIT[@]}; i < $n; ++i )); do
	PLIMIT[$i]=${PLIMIT[$i-1]}
done


echo "CLOCK  = ${CLOCK[*]}"
echo "MEM    = ${MEM[*]}"
echo "FAN    = ${FAN[*]}"
echo "PLIMIT = ${PLIMIT[*]}"

#exit

echo ""
nvidia-persistenced --persistence-mode
nvidia-smi -pm 1

echo ""

#for i in {0..$n}
for (( i=0; i < $n; ++i )); do
	#name=`nvidia-smi --query-gpu=gpu_name,gpu_bus_id --format=csv,noheader -i $i`
	nvidiainfo=`nvidia-smi --query-gpu=gpu_bus_id,gpu_name,power.default_limit,power.limit,power.draw --format=csv,noheader -i $i`
	bus=`awk -F', ' '{print $1}' <<< $nvidiainfo`
	name=`awk -F', ' '{print $2}' <<< $nvidiainfo`
	plim_def=`awk -F', ' '{print $3}' <<< $nvidiainfo`
	plim=`awk -F', ' '{print $4}' <<< $nvidiainfo`
	power_draw=`awk -F', ' '{print $5}' <<< $nvidiainfo`

	bus=`awk '{print substr($1,10); }' <<< $bus` #00000000:01:00.0

	echo -e "${YELLOW}===${NOCOLOR} GPU ${CYAN}$i${NOCOLOR}, $bus ${GREEN}$name${NOCOLOR}, $power_draw / $plim (Default $plim_def) ${YELLOW}=== `date +"%T"`${NOCOLOR}"

	#persistense mode, save settings on process restart
	#nvidia-smi -i $i -pm 1

	#continue

	#power limit
	if [[ ! -z $PLIMIT && ${PLIMIT[$i]} > 0 ]]; then
		nvresult=`nvidia-smi -i $i -pl ${PLIMIT[$i]}`
		[[ $? -ne 0 ]] && color=$RED || color=$NOCOLOR
		nvresult=`echo "$nvresult" | grep -v "^$"`
		echo -e "${color}$nvresult${NOCOLOR}"
	else
		if [[ $plim != $plim_def ]]; then
			echo "Restoring default power limit"
			nvidia-smi -i $i -pl `awk -F' W' '{print $1}' <<< $plim_def` | grep -v "^$"
		fi
	fi

	#not working
	#nvidia-smi -i ${i} -ac 4004,1911

	args=
	#nvidia-settings -a [gpu:$i]/GPUPowerMizerMode=1 | grep -v "^$"
	args+=" -a [gpu:$i]/GPUPowerMizerMode=1"

	if [[ -z $FAN || ${FAN[$i]} == 0 ]]; then
		#nvidia-settings -a [gpu:$i]/GPUFanControlState=0 | grep -v "^$"
		args+=" -a [gpu:$i]/GPUFanControlState=0"
	else
		#nvidia-settings -a [gpu:$i]/GPUFanControlState=1 | grep -v "^$"
		#nvidia-settings -a [fan:$i]/GPUTargetFanSpeed=${FAN[$i]} | grep -v "^$"
		args+=" -a [gpu:$i]/GPUFanControlState=1"
		args+=" -a [fan:$i]/GPUTargetFanSpeed=${FAN[$i]}"
	fi


	#echo "i=$i x=$x"
	#GTX 1050 wanted i=2, allothers want i=3
	x=3
	if [[ $name =~ "1050" ]]; then x=2
	elif [[ $name =~ "P106-100" ]]; then x=2
	elif [[ $name =~ "P106-090" ]]; then x=1
	elif [[ $name =~ "P104-100" ]]; then x=1
	elif [[ $name =~ "P102-100" ]]; then x=1
	fi

	[[ ! -z $CLOCK ]] &&
		#nvidia-settings -a [gpu:$i]/GPUGraphicsClockOffset[$x]=${CLOCK[$i]} | grep -v "^$"
		args+=" -a [gpu:$i]/GPUGraphicsClockOffset[$x]=${CLOCK[$i]}"

	[[ ! -z $MEM ]] &&
		#nvidia-settings -a [gpu:$i]/GPUMemoryTransferRateOffset[$x]=${MEM[$i]} | grep -v "^$"
		args+=" -a [gpu:$i]/GPUMemoryTransferRateOffset[$x]=${MEM[$i]}"


	[[ ! -z $LOGO_BRIGHTNESS ]] &&
		#nvidia-settings -a [gpu:$i]/GPULogoBrightness=$LOGO_BRIGHTNESS | grep -v "^$"
		args+=" -a [gpu:$i]/GPULogoBrightness=$LOGO_BRIGHTNESS"

	if [[ ! -z $args ]]; then
		nvresult=`nvidia-settings $args`
		[[ $? -ne 0 ]] && color=$RED || color=$NOCOLOR
		nvresult=`echo "$nvresult" | grep -v "^$"`
		echo -e "${color}$nvresult${NOCOLOR}"
	fi
done



#
#if [ -z $CPUFREQ ]; then
#    :
#    #echo "WARNING: CPUFREQ not set"
#else
#    :
#    #dont see any improvement with this
#    #cpufreq-set -c 0 -g performance
#    #cpufreq-set -c 1 -g performance
#    #cpufreq-set -c 0 -f 2800Mhz
#    #cpufreq-set -c 1 -f 2800Mhz
#    #echo "performance" >/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
#    #echo "performance" >/sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
#    #echo $CPUFREQ > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
#    #echo $CPUFREQ > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
#fi


exit 0