#!/usr/bin/env bash
# nvidia-oc [index] [busid]

[[ "$1" != "nocolor" ]] && source colors

[[ -f /run/hive/NV_OFF && ! " $@ " =~ " --force " ]] &&
	echo "${YELLOW}NVIDIA driver is disabled. (use ${BYELLOW}--force${YELLOW} to override)${NOCOLOR}" &&
	exit 1

if [[ "$1" == -h || "$1" == --help ]]; then
	echo "Usage: nvidia-info [--force] [index] [busid:00] ..."
	exit 0
fi

date

function nvidiainfo() {
	local nvdata
	readarray -t nvdata < <(nvtool -q --csv --device --busid --name --vbios --temp --fanspeed --fancount --power --curpl \
							--defpl --minmaxpl --clocks --usage --meminfo --memtype --curgen --curwidth --sn --uuid --state --statuscode --status)
	[[ ${#nvdata[@]} -eq 0 ]] && echo -e "${RED}No Nvidia GPUs found or driver not loaded$NOCOLOR" && exit 1

	local nvsinfo
	# Attribute 'GPUTargetFanSpeed' (RIG:0[fan:0]): 56.
	# Attribute 'GPUCurrentFanSpeedRPM' (RIG:0[fan:0]): 1625.
	nvsinfo=`export DISPLAY=:0; nvidia-settings -q GPUTargetFanSpeed -q GPUCurrentFanSpeedRPM 2>/dev/null | grep Attribute`

	local fanidx=0
	declare -A FANS=()

	for gpuinfo in "${nvdata[@]}"; do

		IFS=";" read index busid name bios temp fan fancnt pwr plcur pldef plmin plmax gclk mclk gpuutil memutil memtotal memused memfree\
					memtype pcie linkw sn uuid pstate status msg etc < <( echo "$gpuinfo" )
		[[ -z "$busid" ]] && continue
		busid="${busid#00000000:}" # trim prefix
		# filter output by index or busid
		[[ ! -z "${@//--force}" && (! " $@ " =~ ( $index ) && ! " $@ " =~  ( ${busid/.0} )) ]] && continue

		echo ""

		if [[ $status -ne 0 ]]; then
			echo "${YELLOW}===${NOCOLOR} GPU ${CYAN}${index}${NOCOLOR}, ${PURPLE}${busid} ${GREEN}${name}$NOCOLOR - ${RED}$msg ($status) ${YELLOW}===${NOCOLOR}"
			# let's try to get fans count from gpu-detect
			if [[ $fanidx -ge 0 && ${#FANS[@]} -eq 0 ]]; then
				while IFS=";" read gpu_busid gpu_fans; do
					[[ -z "$gpu_fans" || "$gpu_fans" == "null" ]] && FANS["$gpu_busid"]=1 || FANS["$gpu_busid"]="$gpu_fans"
				done < <( cat $GPU_DETECT_JSON 2>/dev/null | jq -r -c '.[] | (.busid+";"+.fan_cnt)' 2>/dev/null )
			fi
			fancnt=${FANS["$busid"]}
			[[ $fancnt -gt 0 ]] && fanidx=$((fanidx+fancnt)) || fanidx=-1 # disable fan/rpm info as it can be inaccurate
			continue
		fi

		local faninfo=
		if [[ "$fancnt" -gt 0 && $fanidx -ge 0 ]]; then
			for((i=fanidx ; i<fanidx+fancnt; i++ )); do
				readarray -t fanarr < <(echo "$nvsinfo" | grep -oP "\[fan:$i\][^0-9]+\K[0-9]+")
				[[ ${#fanarr[@]} -ne 2 ]] && continue
					faninfo+=", Fan $WHITE${fanarr[0]} %$NOCOLOR, RPM $WHITE${fanarr[1]}$NOCOLOR"
			done
			fanidx=$((fanidx+fancnt))
		fi
		[[ -z "$faninfo" ]] && faninfo=", Fan $WHITE${fan:--} %$NOCOLOR"
		[[ ! -z "$pstate" ]] && pstate="P${pstate}"
		[[ ! -z "$linkw" ]] && linkw="${linkw}x"

		echo "${YELLOW}===${NOCOLOR} GPU ${CYAN}${index}${NOCOLOR}, ${PURPLE}${busid} ${GREEN}${name} ${WHITE}$memtotal MB ${YELLOW}===${NOCOLOR}"
		#echo "Adapter: $index, ${GREEN}$name${NOCOLOR}"
		echo "  Bios $WHITE${bios:--}$NOCOLOR, PCIE Link Gen $WHITE${pcie:--}$NOCOLOR, PCIE Link Width $WHITE${linkw:--}$NOCOLOR"
		echo "  S/N ${serial:--}, UUID ${uuid:--}"
		echo "  Power Limit:  Min $WHITE${plmin:--} W$NOCOLOR, Default $WHITE${pldef:--} W$NOCOLOR, Max $WHITE${plmax:--} W$NOCOLOR, Current $WHITE${plcur:--} W$NOCOLOR"
		echo "  Frequency:  GFXCore $WHITE${gclk:--} MHz$NOCOLOR, MEMCore $WHITE${mclk:--} MHz$NOCOLOR"
		echo "  Memory:  Total $WHITE${memtotal:--} MB$NOCOLOR, Used $WHITE${memused:--} MB$NOCOLOR, Free $WHITE${memfree:--} MB$NOCOLOR, $WHITE${memtype:--}$NOCOLOR"
		echo "  Utilization:  GPU $WHITE${gpuutil:--} %$NOCOLOR, MEM $WHITE${memutil:--} %$NOCOLOR"
		echo "  PSTATE ${WHITE}${pstate:--}$NOCOLOR, PWR $WHITE${pwr:--} W$NOCOLOR, Temp $WHITE${temp:--} °C$NOCOLOR$faninfo"

	done
}


nvidiainfo $@

