#!/usr/bin/env bash
#we don't care about interface so wont use /lib/systemd/systemd-networkd-wait-online

export PATH="./:/hive/bin:/hive/sbin:$PATH"

#[ -t 1 ] &&
. colors #use them anyway

function echo2 {
	echo -e "$1" > /dev/tty1
	echo -e "$1"
}


host=1.1.1.1
#nslookuphost=hiveos.farm
nslookuphost=hiveos.farm
#wifi_active=`systemctl is-active wpa_supplicant@wlan0.service`


check_online() {
#	ping -n -c 1 -w 1 $host > /dev/null 2>&1
# returns "Network unreachable" and does not wait
#	sleep 1

	#ICMP can be blocked in datacenters so we need to use something else

	timeout 5 nslookup $nslookuphost > /dev/null 2>&1
	exitcode=$?
	[[ $exitcode -ne 0 ]] && echo "nslookup $nslookuphost failed"
	return $exitcode
}

# Do you want a timeout ?
for i in {1..6}; do
	check_online &&
		echo2 "${GREEN}Network is online${NOCOLOR}" &&
		exit 0

	[[ $i -ge 1 ]] &&
		echo2 "Waiting for online... $i"
done


echo2 "${RED}Network is offline, check your Internet connection${NOCOLOR}"

exit 1