#!/bin/bash


    case $1 in
	on)
	    echo  "Switch On to wd based on arduino nano"
	    touch /hive-config/WD-NANO 
	;;
	off)
	    echo  "Switch Off to wd based on arduino nano"
	    rm -f /hive-config/WD-NANO
	;;
	*)
	    echo  "Usage : $0 on , or $0 off  to On or Off detect china WD based on Arduio nano"  
	;;
    esac