#!/usr/bin/env bash

SERVICE_NAME=wpa_supplicant@wlan0

systemctl stop $SERVICE_NAME

systemctl is-enabled $SERVICE_NAME > /dev/null
[[ $? == 0 ]] && # 1 - disabled
	systemctl disable $SERVICE_NAME &&
	echo "WiFi $SERVICE_NAME service disabled"
