#!/usr/bin/env bash

[[ -z $1 ]] &&
	echo "Usage: `basename $0` ping|reset [port]" &&
	exit 1

PORT=/dev/china_dog0

[[ ! -z $2 ]] &&
	PORT=$2 ||
	echo "No port given, using default"

echo "Using $PORT"



[[ ! -c $PORT ]] &&
	echo "$PORT is not a character device" &&
	exit 1


if [[ -e /hive-config/watchdog/wd-nano.on ]]; then
	# Arduino nano
	ping="r90p90"
	reset="r2p90"
elif [[ -e /hive-config/watchdog/wd-fixorgua.on ]]; then
	# FixOrgUa
	#https://fix.org.ua/index.php/fix-forum/tekhpodderzhka/67-po-dlya-watchdog?start=6#135
	ping="\x31\x41"
	reset="\x33\x33"
else
	# Default China dog
	ping="\x1E\x00"
	reset="\xFF\x55"
fi


if [[ $1 == "reset" ]]; then
	echo "Pushing Reset"
	echo -ne $reset > $PORT
	exit 0
fi


#if [[ $1 == "power" ]]; then
#        echo "Pushing Power"
#        echo -n "~T2" > $PORT
#        exit 0
#fi


#should be ping here, but will work with any
#Send 60 second timeout to WD in HEX , if WD does not receive 2*timeout, then WD RESET the MB.

while true; do
	echo "Pinging watchdog"
	echo -ne $ping > $PORT
	sleep 5
done
