#!/usr/bin/env bash

[[ -z $1 ]] &&
	echo "Usage: `basename $0` ping|reset [port]" &&
	exit 1

PORT=/dev/china_dog0

[[ ! -z $2 ]] &&
	PORT=$2 ||
	echo "No port given, using default"

echo "Using $PORT"



[[ ! -c $PORT ]] &&
	echo "$PORT is not a character device" &&
	exit 1


if [[ -e /hive-config/watchdog/wd-nano.on ]]; then
	# Arduino nano
	ping="r90p90"
	reset="r2p90"
elif [[ -e /hive-config/watchdog/wd-fixorgua.on ]]; then
	# FixOrgUa
	#https://fix.org.ua/index.php/fix-forum/tekhpodderzhka/67-po-dlya-watchdog?start=6#135
	ping="\x31\x41"
	reset="\x33\x33"
else
	# Default China dog
	ping="\x1E\x00"
	reset="\xFF\x55"
fi


if [[ $1 == "reset" ]]; then
	echo "Pushing Reset"
	echo -ne $reset > $PORT
	exit 0
fi


#if [[ $1 == "power" ]]; then
#        echo "Pushing Power"
#        echo -n "~T2" > $PORT
#        exit 0
#fi


#should be ping here, but will work with any
#if port 22 (ssh) responds then
#send 60 second timeout to WD in HEX , if WD does not receive 2*timeout, then WD RESET the MB.

#while true; do
#	echo "Pinging watchdog"
#	[[ `nc -w 2 -zv localhost 22 2>&1 | grep -c succeeded` -gt 0 ]] && echo -ne $ping > $PORT
#	sleep 5
#done

pinging=1
port=22
while true
do
	t1=`date +%s` || t1=0
	if [[ $pinging -eq 1 ]] && nc -w 1 -z localhost $port 2>&1; then
		echo "Pinging watchdog"
		echo -ne $ping > $PORT || break;
	else
		echo "NOT pinging watchdog (sshd port $port)"
		port=`cat /etc/ssh/sshd_config 2>/dev/null | grep -oP "^Port[\s]+\K[0-9]+"`
	fi
	sleep 5
	t2=`date +%s` || t2=0
	[[ $t2 -eq 0 || $t1 -eq 0 || $(( t2 - t1 )) -ge 10 ]] && pinging=0 || pinging=1
done

message error "hl340 wd error"
